name: Publish

on: [push]

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: cfa-release
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - uses: actions/checkout@v4
      - uses: continuousauth/action@main
        with:
          project-id: ${{ secrets.CFA_PROJECT_ID }}
          secret: ${{ secrets.CFA_SECRET }}

