name: Publish

on: [push]

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: continuousauth/action@main
        with:
          project-id: ${{ secrets.CFA_PROJECT_ID }}
          secret: ${{ secrets.CFA_SECRET }}
          npm-token: ${{ secrets.NPM_TOKEN }}

